### просмотр списка фильмов

GET {{url}}/films

### невалидная запись о фильме

POST {{url}}/films
Content-Type: application/json

{
  "id": -10,
  "title": null,
  "description": null,
  "image": null,
  "trailer": null,
  "genres": null
}

### невалидная запись о фильме

POST {{url}}/films
Content-Type: application/json

{
  "id": 0,
  "title": "",
  "description": "",
  "image": null,
  "trailer": null,
  "genres": []
}

###